### PR TITLE
Test for the action #1

### PR DESCRIPTION
**Pull request by dpnkrpl**
Testing the action by adding files to `test` the directory.

### CODE REVIEW

**Comment by dpnkrpl** [comment]
test after fixing workflowfile

**Comment by dpnkrpl** [comment]
updating `dist/index.js` to reflect changes and trying again

**Comment by dpnkrpl** [comment]
testing again

**Comment by dpnkrpl** [comment]
fixed all import issues

**Comment by dpnkrpl** [comment]
fixed: console.warning()

**Comment by deep5050** [comment]
testing again

**Pull request closed without merging**
